class Tokens:
    tokens = [
        "LLAVE_ABRE",
        "LLAVE_CIERRA",
        "COMA",
        "DOS_PUNTOS",
        "ENTERO",
        "DECIMAL",
        "CADENA_COMILLAS",
        "CADENA_NO_COMILLAS",
        "IGUAL",
        "MAYOR",
        "MENOR",
        "MAYOR_IGUAL",
        "MENOR_IGUAL",
        "CORCHETE_ABRE",
        "CORCHETE_CIERRA",
        "PUNTO_Y_COMA",
        "PUNTO",
        "PARENTESIS_ABRE",
        "PARENTESIS_CIERRA",
        "COMENTARIO_LINEA",
        "COMENTARIO_BLOQUE",
        "CONJUNCION",
        "DISYUNCION",
        "NEGACION",
        "SUMA",
        "RESTA",
        "MULTIPLICACION",
        "DIVISION",
        "ASIGNACION",
        "CARACTER"
    ]

    reserved = ["TR", "FL", "LET", "INT", "FLOAT", "CHARACTER",
                 "WHILE", "BOOLEAN", "FUNCTION", "RETURN", "TYPE",
                 "IF", "ELSE", "NULL"] 